### ISSUE TITLE
メッセージをメッセージ送信者にのみ表示できない

### ISSUE THREAD

**Issue by kabikabichan** [CyberRex0/discord-ia-button-module#3]
クリックイベントを受信し、`event.reply(text, hidden=True)`としても全員に表示されてしまいます

**Comment by CyberRex0** [comment]
https://github.com/CyberRex0/discord-ia-button-module/commit/f9913beaf78c5d5e3a53bb4d0713627e93ada5bc#diff-6e491c02882ac36e3bcaaac4d151d4b2793135d4482adf227b1b730cdd90b46d
このバグは上記コミットで修正されました。
報告ありがとうございました。
